services:
  Kolyya\FixturesHelperBundle\Command\FixturesLoadCommand:
    tags:
      name: console.command
      command: kolyya:fixtures:load
    arguments:
      $backupPath: '%kolyya_fixtures_helper.backup_path%'
      $doctrine: '@doctrine'
      $loadConfig: '%kolyya_fixtures_helper.load%'

  Kolyya\FixturesHelperBundle\Service\UploaderHelper:
    arguments:
      $kernelProjectDir: '%kernel.project_dir%'
